### PR TITLE
add dev environment configuration

### PR DESCRIPTION
**Pull request by apavlidi**
Here is the task: https://trello.com/c/owdC7Hw4

### CODE REVIEW

**Comment by apavlidi** [comment]
> In WebDevConfig we also need bean for CORS filter. Even if this allowed to get cards locally it block other request without

Did you test it locally?

**Comment by apavlidi** [comment]
> In WebDevConfig we also need bean for CORS filter. Even if this allowed to get cards locally it block other request without

Can you please give me more info so I can reproduce the problem locally?

**Comment by Morinslash** [comment]
lunch backend in devmode and then open frontend, when you try to delete or edit card request will be rejected by CORS policy on backend

**Comment by apavlidi** [comment]
> lunch backend in devmode and then open frontend, when you try to delete or edit card request will be rejected by CORS policy on backend

It runs for me fine. Are you sure you are running on dev profile?
Screenshot from 2020-06-02 11-01-30

Please make run on dev mode, one solution might be by adding a jvm option like the image below
Screenshot from 2020-06-02 11-02-00

**Pull request merged**
